services:
  - type: web
    name: fatwa-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COHERE_API_KEY
        value: aoQCSHKFoL1AQZfds9WZCV8ELYgtWKxrVNb0G19z
        sync: false
  - type: web
    name: fatwa-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist